# Generated by Django 3.1.7 on 2021-03-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210317_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='themes',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
