# Generated by Django 3.1.7 on 2021-03-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_themes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='themes',
            new_name='theme',
        ),
    ]
