# Generated by Django 3.1.7 on 2021-03-10 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210309_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='child_posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_post', to='main.post'),
        ),
    ]
