# Generated by Django 3.1.7 on 2021-03-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210319_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='post_pics'),
        ),
    ]
