# Generated by Django 3.1.7 on 2021-03-10 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_child_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='child_posts',
        ),
        migrations.AddField(
            model_name='post',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_posts', to='main.post'),
        ),
    ]
